Upper limit on pymatgen due to breaking change
```python
ValueError                                Traceback (most recent call last)
<ipython-input-3-173282f428cf> in <cell line: 2>()
      1 from matbench_genmetrics.mp_time_split.utils.gen import DummyGenerator
----> 2 from matbench_genmetrics.core.metrics import MPTSMetrics10
      3 from tqdm.notebook import tqdm
      4 from pprint import pprint

8 frames
/usr/local/lib/python3.10/dist-packages/pymatgen/core/periodic_table.py in from_Z(Z, A)
    524             if data["Atomic no"] == Z and atomic_mass_num == A:
    525                 return Element(sym)
--> 526         raise ValueError(f"Unexpected atomic number {Z=}")
    527 
    528     @staticmethod

ValueError: Unexpected atomic number Z=119
```